const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('coreShiftAPI', {
  getSystemStats: () => ipcRenderer.invoke('system:getStats'),
  runBoost: () => ipcRenderer.invoke('system:boost'),
  applyFpsOptions: (options) => ipcRenderer.invoke('system:applyFpsOptions', options),
  cleanRam: () => ipcRenderer.invoke('system:cleanRam'),
  getBoosterState: () => ipcRenderer.invoke('booster:state'),
  saveBoosterConfig: (config) => ipcRenderer.invoke('booster:config:save', config),
  applyBooster: (config) => ipcRenderer.invoke('booster:apply', { config }),
  restoreBooster: () => ipcRenderer.invoke('booster:restore'),
  chooseBoosterGame: () => ipcRenderer.invoke('booster:game:choose'),
  launchBoosterGame: () => ipcRenderer.invoke('booster:game:launch'),
  listBoosterProcesses: () => ipcRenderer.invoke('booster:processes'),
  scanGameLibrary: () => ipcRenderer.invoke('library:scan'),
  addLibraryGame: () => ipcRenderer.invoke('library:add'),
  toggleLibraryFavorite: (id) => ipcRenderer.invoke('library:favorite', { id }),
  launchLibraryGame: (id) => ipcRenderer.invoke('library:launch', { id }),
  getLibraryPlatforms: () => ipcRenderer.invoke('library:platforms'),
  openLibraryPlatform: (id) => ipcRenderer.invoke('library:platform:open', { id }),
  openLibraryDestination: (id) => ipcRenderer.invoke('library:destination:open', { id }),
  getCaptureSources: () => ipcRenderer.invoke('clips:getSources'),
  importClip: () => ipcRenderer.invoke('clips:import'),
  saveClip: (arrayBuffer, options = {}) => ipcRenderer.invoke('clips:save', { arrayBuffer, name: options.name, metadata: options.metadata }),
  exportClip: (payload) => ipcRenderer.invoke('clips:export', payload),
  mergeReplay: (payload) => ipcRenderer.invoke('clips:mergeReplay', payload),
  cancelClipExport: () => ipcRenderer.invoke('clips:cancelExport'),
  onClipExportProgress: (callback) => ipcRenderer.on('clips:exportProgress', (_event, progress) => callback(progress)),
  onSaveReplayHotkey: (callback) => ipcRenderer.on('clips:saveReplayHotkey', callback),
  listClips: () => ipcRenderer.invoke('clips:list'),
  readClip: (filePath) => ipcRenderer.invoke('clips:read', filePath),
  deleteClip: (filePath) => ipcRenderer.invoke('clips:delete', filePath),
  openClipsFolder: () => ipcRenderer.invoke('clips:openFolder'),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (updates) => ipcRenderer.invoke('settings:save', updates),
  connectDatabase: (config) => ipcRenderer.invoke('db:connect', config),
  detectDatabase: () => ipcRenderer.invoke('db:detect'),
  getDatabaseTables: () => ipcRenderer.invoke('db:tables'),
  runDatabaseQuery: (sql) => ipcRenderer.invoke('db:query', sql),
  loadChat: (channel) => ipcRenderer.invoke('chat:load', channel),
  sendChat: (message) => ipcRenderer.invoke('chat:send', message),
  registerAccount: (payload) => ipcRenderer.invoke('auth:register', payload),
  loginAccount: (payload) => ipcRenderer.invoke('auth:login', payload),
  getAccountSession: () => ipcRenderer.invoke('auth:session'),
  logoutAccount: () => ipcRenderer.invoke('auth:logout'),
  getLoginAudit: () => ipcRenderer.invoke('auth:audit'),
  recordConsent: (termsVersion) => ipcRenderer.invoke('audit:consent', termsVersion),
  getAccounts: () => ipcRenderer.invoke('auth:users'),
  setAccountRole: (payload) => ipcRenderer.invoke('auth:setRole', payload),
  loadContent: () => ipcRenderer.invoke('content:load'),
  saveContent: (key, value) => ipcRenderer.invoke('content:save', key, value),
  sendFeedback: (feedback) => ipcRenderer.invoke('feedback:send', feedback),
  listCrosshairs: () => ipcRenderer.invoke('crosshair:list'),
  saveCrosshair: (preset) => ipcRenderer.invoke('crosshair:save', preset),
  deleteCrosshair: (id) => ipcRenderer.invoke('crosshair:delete', id),
  toggleCrosshair: (enabled) => ipcRenderer.invoke('crosshair:toggle', enabled),
  updateCrosshairOverlay: (preset) => ipcRenderer.send('crosshair:updateOverlay', preset),
  importCrosshair: () => ipcRenderer.invoke('crosshair:import'),
  onCrosshairPreset: (callback) => ipcRenderer.on('crosshair:preset', (_event, preset) => callback(preset)),
  toggleOverlay: (enabled) => ipcRenderer.invoke('overlay:toggle', enabled),
  sendOverlayStats: (stats) => ipcRenderer.send('overlay:stats', stats),
  onOverlayStats: (callback) => ipcRenderer.on('overlay:stats', (_event, stats) => callback(stats)),
  chooseSecurityFile: () => ipcRenderer.invoke('security:chooseFile'),
  scanSecurityFile: (payload) => ipcRenderer.invoke('security:scanFile', payload),
  scanSecurityUrl: (payload) => ipcRenderer.invoke('security:scanUrl', payload),
  getSecurityAnalysis: (payload) => ipcRenderer.invoke('security:analysis', payload),
  connectDiscordPresence: (payload) => ipcRenderer.invoke('discord:connect', payload),
  disconnectDiscordPresence: () => ipcRenderer.invoke('discord:disconnect'),
  getDiscordPresenceStatus: () => ipcRenderer.invoke('discord:status'),
  onDiscordPresenceStatus: (callback) => ipcRenderer.on('discord:statusChanged', (_event, status) => callback(status)),
  getDiscordBotStatus: () => ipcRenderer.invoke('bot:status'),
  saveDiscordBotConfig: (payload) => ipcRenderer.invoke('bot:config:save', payload),
  startDiscordBot: () => ipcRenderer.invoke('bot:start'),
  stopDiscordBot: () => ipcRenderer.invoke('bot:stop'),
  getDiscordBotInvite: () => ipcRenderer.invoke('bot:invite'),
  registerDiscordBotCommands: () => ipcRenderer.invoke('bot:commands:register'),
  inspectDiscordBotCommands: () => ipcRenderer.invoke('bot:commands:inspect'),
  onDiscordBotStatus: (callback) => ipcRenderer.on('bot:statusChanged', (_event, status) => callback(status)),
  getIpPrivacyStatus: () => ipcRenderer.invoke('ipPrivacy:status'),
  listVpnProfiles: () => ipcRenderer.invoke('ipPrivacy:profiles'),
  saveIpPrivacyConfig: (payload) => ipcRenderer.invoke('ipPrivacy:config:save', payload),
  rotatePublicIp: () => ipcRenderer.invoke('ipPrivacy:rotate'),
  checkPublicIp: () => ipcRenderer.invoke('ipPrivacy:publicIp'),
  openWindowsVpnSettings: () => ipcRenderer.invoke('ipPrivacy:openSettings'),
  onIpPrivacyStatus: (callback) => ipcRenderer.on('ipPrivacy:statusChanged', (_event, status) => callback(status)),
  getUpdateConfiguration: () => ipcRenderer.invoke('updates:config:get'),
  saveUpdateConfiguration: (payload) => ipcRenderer.invoke('updates:config:save', payload),
  checkForUpdates: () => ipcRenderer.invoke('updates:check'),
  downloadUpdate: () => ipcRenderer.invoke('updates:download'),
  installUpdate: () => ipcRenderer.invoke('updates:install'),
  getUpdateStatus: () => ipcRenderer.invoke('updates:status'),
  getMobileControlStatus: () => ipcRenderer.invoke('mobile:status'),
  startMobileControl: () => ipcRenderer.invoke('mobile:start'),
  stopMobileControl: () => ipcRenderer.invoke('mobile:stop'),
  resetMobileControlPairing: () => ipcRenderer.invoke('mobile:pairing:reset'),
  onUpdateStatus: (callback) => ipcRenderer.on('updates:statusChanged', (_event, status) => callback(status)),
  testLatency: (payload) => ipcRenderer.invoke('network:ping', payload),
  getNetworkInfo: () => ipcRenderer.invoke('network:info'),
  flushDnsCache: () => ipcRenderer.invoke('network:flushDns'),
  loadPiaPanel: () => ipcRenderer.invoke('pia:panel'),
  listPiaLinks: () => ipcRenderer.invoke('pia:links:list'),
  savePiaLink: (payload) => ipcRenderer.invoke('pia:links:save', payload),
  deletePiaLink: (id) => ipcRenderer.invoke('pia:links:delete', { id }),
  listPiaFormats: () => ipcRenderer.invoke('pia:formats:list'),
  savePiaFormat: (payload) => ipcRenderer.invoke('pia:formats:save', payload),
  deletePiaFormat: (id) => ipcRenderer.invoke('pia:formats:delete', { id }),
  minimizeWindow: () => ipcRenderer.send('window:minimize'),
  closeWindow: () => ipcRenderer.send('window:close')
});
